url: https://new.asw.io
baseurl: ""

# Site settings
title: Arne Schauf
email: info@asw.io
description: "Arne Schauf: Software Developer - Tech Geek - Digital Automation Engineer"


# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: xing
    url: https://www.xing.com/profile/Arne_Schauf/
  - title: github
    url: http://github.com/asmaps
  - title: linkedin
    url: https://de.linkedin.com/in/arne-schauf-0a622a57
  - title: bitbucket 
    url: http://bitbucket.org/asmaps
  - title: twitter
    url: http://twitter.com/asmaps

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
